const employeeHeader = [
	'SBU Name',
	'Employee ID',
	'EUserID',
	'Salutation',
	'FirstName',
	'MiddleName',
	'LastName',
	'Date Of Joining',
	'Date Of Birth',
	'Gender',
	'Personal Email ID',
	'Contact No',
	'State',
	'City',
	'Current Address',
	'Permanent Address',
	'Branch',
	'Department',
	'Sub-Department',
	'Designation',
	'Official Email ID',
	'Grade',
	'Employee Type',
	'Employment Type',
	'Is Probation',
	'Probation Date',
	'Reporting Manager-1',
	'Reporting Manager-2',
	'PAN No',
	'ESIC Applicable',
	'ESIC No',
	'PF Applicable',
	'PF No',
	'PF Spe. Applicable',
	'Gratuity Applicable',
	'UAN No',
	'Aadhar No',
];

// export
module.exports = {
	employeeHeader,
};